default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= Rails.application.credentials.fetch(:database).fetch(:host) %>
  username: <%= Rails.application.credentials.fetch(:database).fetch(:username) %>
  password: <%= Rails.application.credentials.fetch(:database).fetch(:password) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.fetch(:database).fetch(:name) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.fetch(:database).fetch(:name) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.fetch(:database).fetch(:name) %>
