default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_HOST") { Rails.application.credentials.fetch(:database).fetch(:host) } %>
  username: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_USERNAME") { Rails.application.credentials.fetch(:database).fetch(:username) } %>
  password: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_PASSWORD") { Rails.application.credentials.fetch(:database).fetch(:password) } %>
  gssencmode: disable

development:
  <<: *default
  database: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_NAME") { Rails.application.credentials.fetch(:database).fetch(:name) } %>

docker:
  <<: *default
  database: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_NAME") { Rails.application.credentials.fetch(:database).fetch(:name) } %>

test:
  <<: *default
  database: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_NAME") { Rails.application.credentials.fetch(:database).fetch(:name) } %>

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] ? nil : ENV.fetch("DATABASE_NAME") { Rails.application.credentials.fetch(:database).fetch(:name) } %>
